#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: stable/12/usr.bin/comm/Makefile 322515 2017-08-14 19:21:37Z ngie $

.include <src.opts.mk>

PROG=	comm

HAS_TESTS=
SUBDIR.${MK_TESTS}+= tests

.include <bsd.prog.mk>
