# $FreeBSD: stable/12/usr.bin/clang/llvm-cxxfilt/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-cxxfilt
MAN=

SRCDIR=		llvm/tools/llvm-cxxfilt
SRCS+=		llvm-cxxfilt.cpp

.include "../llvm.prog.mk"
