# $FreeBSD: stable/12/usr.bin/clang/llvm-symbolizer/Makefile 356462 2020-01-07 19:49:10Z dim $

PROG_CXX=	llvm-symbolizer

SRCDIR=		llvm/tools/llvm-symbolizer
SRCS+=		llvm-symbolizer.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
